#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cebuanizer.Resource", IsApplication=true)]

namespace Cebuanizer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int customFont = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonMenuStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int coin_small = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int home = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_large = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_small = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int LayoutBackground = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int slogan = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070015
			public const int button1 = 2131165205;
			
			// aapt resource value: 0x7f070022
			public const int button2 = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int button3 = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int button4 = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int button5 = 2131165221;
			
			// aapt resource value: 0x7f070018
			public const int editText1 = 2131165208;
			
			// aapt resource value: 0x7f070009
			public const int etSearch = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int imageView1 = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int imageView2 = 2131165189;
			
			// aapt resource value: 0x7f070033
			public const int lbtnAchievements = 2131165235;
			
			// aapt resource value: 0x7f070031
			public const int lbtnDictionary = 2131165233;
			
			// aapt resource value: 0x7f07001e
			public const int lbtnFSubmit = 2131165214;
			
			// aapt resource value: 0x7f070014
			public const int lbtnGOne = 2131165204;
			
			// aapt resource value: 0x7f070032
			public const int lbtnPhrases = 2131165234;
			
			// aapt resource value: 0x7f070030
			public const int lbtnPlay = 2131165232;
			
			// aapt resource value: 0x7f07002b
			public const int lbtnTOk = 2131165227;
			
			// aapt resource value: 0x7f070003
			public const int limgCoinIcon = 2131165187;
			
			// aapt resource value: 0x7f07001a
			public const int limgFCoin = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int limgFHome = 2131165209;
			
			// aapt resource value: 0x7f070010
			public const int limgGCoin = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int limgGHome = 2131165199;
			
			// aapt resource value: 0x7f070020
			public const int limgGMCoin = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int limgGMHome = 2131165215;
			
			// aapt resource value: 0x7f070027
			public const int limgGTCoin = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int limgGTHome = 2131165222;
			
			// aapt resource value: 0x7f070008
			public const int limgHome = 2131165192;
			
			// aapt resource value: 0x7f070039
			public const int limgIcon = 2131165241;
			
			// aapt resource value: 0x7f07002f
			public const int limgMenuSlogan = 2131165231;
			
			// aapt resource value: 0x7f070037
			public const int limgPHome = 2131165239;
			
			// aapt resource value: 0x7f07003a
			public const int limgSlogan = 2131165242;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout2 = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout3 = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout4 = 2131165202;
			
			// aapt resource value: 0x7f070016
			public const int linearLayout5 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout6 = 2131165207;
			
			// aapt resource value: 0x7f070013
			public const int linearLayout7 = 2131165203;
			
			// aapt resource value: 0x7f070035
			public const int listPCeb = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int listPTag = 2131165238;
			
			// aapt resource value: 0x7f07000e
			public const int listTextCeb = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int listTextTag = 2131165197;
			
			// aapt resource value: 0x7f070038
			public const int llstPhrases = 2131165240;
			
			// aapt resource value: 0x7f07000c
			public const int llstWords = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int ltxtCoin = 2131165188;
			
			// aapt resource value: 0x7f07001b
			public const int ltxtFCoin = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int ltxtFInput = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int ltxtFSentence = 2131165212;
			
			// aapt resource value: 0x7f070011
			public const int ltxtGCoin = 2131165201;
			
			// aapt resource value: 0x7f070028
			public const int ltxtGTCoin = 2131165224;
			
			// aapt resource value: 0x7f070021
			public const int ltxtMCoin = 2131165217;
			
			// aapt resource value: 0x7f070029
			public const int ltxtTSentence = 2131165225;
			
			// aapt resource value: 0x7f07002c
			public const int ltxtTWord1 = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int ltxtTWord2 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int ltxtTWord3 = 2131165230;
			
			// aapt resource value: 0x7f070034
			public const int ltxtTip = 2131165236;
			
			// aapt resource value: 0x7f07002a
			public const int ltxtbTAnswer = 2131165226;
			
			// aapt resource value: 0x7f070006
			public const int textView1 = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int textView2 = 2131165194;
			
			// aapt resource value: 0x7f07003b
			public const int txtTrivia = 2131165243;
			
			// aapt resource value: 0x7f07000b
			public const int view1 = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Achievements = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Dictionary = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int DictListRow = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Game = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int GameFill = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int GameFill2 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int GameMatching = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int GameTranslation = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Menu = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int PhraListRow = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Phrases = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int StartUp = 2130968587;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int buttontap = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cebuano_my_name_is_Maya = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cebuano_woman = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int Good_Afternoon = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Good_Day = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Good_Evening = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Good_Luck = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Good_Morning = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Hello = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int I_dont = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Im_Okay = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int My_Name = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int Name = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int No_See = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int understand = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Welcome = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int Where = 2131034128;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CustomFonts = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int CustomFonts_customFont = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
